version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    command: ["sh", "-c", "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:80 book_management.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - MONGO_URI=${MONGO_URI}  # Lee la variable MONGO_URI del archivo .env
    networks:
      - book_management_network
    depends_on:
      - mongo  # Asegura que MongoDB esté disponible antes de Django

  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    networks:
      - book_management_network

networks:
  book_management_network:
    driver: bridge

volumes:
  mongo_data: